# fly.toml app configuration file generated for mar257chatbot on 2024-03-08T19:13:10+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mar257chatbot'
primary_region = 'hkg'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
