# fly.toml app configuration file generated for chatbot-257 on 2024-03-08T19:46:46+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'chatbot-257'
primary_region = 'hkg'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'

[[services]]
  internal_port = 8000
  protocol = 'tcp'

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [[services.ports]]
    handlers = ["http"]
    port = 80

[[vm]]
  size = 'shared-cpu-1x'
